services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile

    image: rag-pdf-qa-service:1.0

    container_name: rag-pdf-qa-container

    env_file:
      - .env

    ports:
      - "8000:8000"

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s